### ISSUE TITLE
Option to scrape and download only exclusive videos

### ISSUE THREAD

**Issue by Rexathion1** [vapronva/nebula_tv_downloader-media_api#1]
Hi there vapronva , I was wondering if you can add a option to only get exclusives . Because only they are worth archiving as every other video is available elsewhere , i tried modifying the config.py and replaced the video feed url :
`NEBULA_API_CONTENT_ALL_VIDEOS = parse_obj_as(
    HttpUrl, "https://content.api.nebula.app/video/?category=originals"
)
`

It seemed to work as number of videos shown in log were reduced to just 300 instead of 13000 but when it started actually saving stream info all videos were scraped instead of only exclusives . I dont know python else i would have loved to contribute myself . Anyways thanks for your work , if you have some time consider adding this feature

**Comment by vapronva** [comment]
Oh, hello! \
Thanks for checking the "project" out.

Yes, I might try adding the filtering soon. As well as make it more usable for a public usage…

Will update you once it's done.

**Comment by vapronva** [comment]
@Rexathion1, changed the logic a bit: now it's possible to define certain channels for downloading, apply filters (for `Plus` / `First` / `Originals` videos) via a single configuration file. \
Updated the README to reflect the changes!

Unfortunately, the tool still assumes downloading of all videos from a channel. \
Let me know if that's also what you want to be changed.

**Comment by Rexathion1** [comment]
Thanks for the update ! it is exactly what i wanted
